### ISSUE TITLE
Compatibility with earlier versions of Laravel?

### ISSUE THREAD

**Issue by jezmck** [inFureal/artisan-gui#7]
Are there difficult to solve problems preventing this package being compatible with earlier versions of Laravel?

**Comment by inFureal** [comment]
Sorry, but I haven't any plans to support older versions of Laravel because of deprecated packages and code in it.
Highly recomended to upgrade your code to latest version of laravel.

If you need you can `[fork this package/clone and create local repo]`, downgrade version for your needs and hope that something not broken.
