### ISSUE TITLE
can we run custom comands?

### ISSUE THREAD

**Issue by jechaviz** [inFureal/artisan-gui#8]
let's say vendor/composer packages comands in some order, like a script?

**Comment by inFureal** [comment]
If you think about something like `git init` or `npm install` etc. - that is not working like that.
This package only runs commands that registered in your application, otherwise registered in ServiceProviders/ConsoleKernel.

If needed, you can publish config `php artisan vendor:publish --tag="artisan-gui-config"` and customize commands relying on your needs.
